### ISSUE TITLE
Map: potential decade divisions

### ISSUE THREAD

**Issue by karindalziel** [CDRH/family_letters#166]
Potential division: 

Pre 1930
1930s
1940s
1950s
1960s
1970s
1980s
Post 1989

Pre 1930  - 14
1930s     - 74
1940s     - 104
1950s     - 178
1960s     - 72
1970s     - 31
1980s     - 7
Post 1989 - 17

---

1900's

1900 1
1905 1

---

1910's

1919 1

---

1920's

1920 3
1923 2
1926 3
1927 2
1928 1

---

1930's

1930 4
1933 1
1934 3
1936 3
1937 18
1938 15
1939 30

---

1940's

1940 10
1941 5
1942 15
1943 12
1944 7
1945 12
1946 19
1947 6
1948 14
1949 4

---

1950's

1950 24
1951 5
1952 14
1953 12
1954 7
1955 5
1956 7
1957 16
1958 16
1959 17

---

1960's

1960 4
1961 10
1962 13
1963 8
1964 5
1965 8
1966 8
1967 5
1968 5
1969 6

---

1970's

1970 6
1971 3
1973 1
1974 5
1975 3
1976 6
1977 6
1978 1

---

1980's

1982 4
1983 1
1984 1
1986 1

---

1990's

1996 1

---

2000's

2000 1

---

2010's

2012 1
2014 1
2019 13

**Comment by jduss4** [comment]
At the moment I just have simple decade breakdowns, but let me know if we need to change the ranges
